# Введение в Машинное обучение

## Высшая Школа Цифровой Культуры

## Материалы к лекции 2. Линейная регрессия

### Примеры 

In [1]:
#чтение данных, так как названия конфет уникальны, используем их в качестве индекса
import pandas as pd
DATA = pd.read_csv("ITMO Week 4 candy-data.csv", delimiter=',', index_col='competitorname')

In [2]:
DATA

chocolate  fruity  caramel  peanutyalmondy  nougat  \
competitorname                                                              
100 Grand                      1       0        1               0       0   
3 Musketeers                   1       0        0               0       1   
One dime                       0       0        0               0       0   
One quarter                    0       0        0               0       0   
Air Heads                      0       1        0               0       0   
...                          ...     ...      ...             ...     ...   
Snickers Crisper               1       0        1               1       0   
Sour Patch Kids                0       1        0               0       0   
Sour Patch Tricksters          0       1        0               0       0   
Starburst                      0       1        0               0       0   
Strawberry bon bons            0       1        0               0       0   

                       crispedricewafer  hard  bar  pluribus  sugarpercent  \
competitorname                                                               
100 Grand                             1     0    1         0         0.732   
3 Musketeers                          0     0    1         0         0.604   
One dime                              0     0    0         0         0.011   
One quarter                           0     0    0         0         0.011   
Air Heads                             0     0    0         0         0.906   
...                                 ...   ...  ...       ...           ...   
Snickers Crisper                      1     0    1         0         0.604   
Sour Patch Kids                       0     0    0         1         0.069   
Sour Patch Tricksters                 0     0    0         1         0.069   
Starburst                             0     0    0         1         0.151   
Strawberry bon bons                   0     1    0         1         0.569   

                       pricepercent  winpercent  Y  
competitorname                                      
100 Grand                     0.860   66.971725  1  
3 Musketeers                  0.511   67.602936  1  
One dime                      0.116   32.261086  0  
One quarter                   0.511   46.116505  0  
Air Heads                     0.511   52.341465  1  
...                             ...         ... ..  
Snickers Crisper              0.651   59.529251  1  
Sour Patch Kids               0.116   59.863998  1  
Sour Patch Tricksters         0.116   52.825947  1  
Starburst                     0.220   67.037628  1  
Strawberry bon bons           0.058   34.578991  0  

[70 rows x 13 columns]

In [3]:
#обучение модели будем проводить на данных, за исключением некоторых конфет
train_data = DATA.drop(['100 Grand','3 Musketeers','One dime','One quarter','Air Heads'])

In [4]:
train_data

chocolate  fruity  caramel  peanutyalmondy  nougat  \
competitorname                                                              
Almond Joy                     1       0        0               1       0   
Baby Ruth                      1       0        1               1       1   
Boston Baked Beans             0       0        0               1       0   
Candy Corn                     0       0        0               0       0   
Caramel Apple Pops             0       1        1               0       0   
...                          ...     ...      ...             ...     ...   
Snickers Crisper               1       0        1               1       0   
Sour Patch Kids                0       1        0               0       0   
Sour Patch Tricksters          0       1        0               0       0   
Starburst                      0       1        0               0       0   
Strawberry bon bons            0       1        0               0       0   

                       crispedricewafer  hard  bar  pluribus  sugarpercent  \
competitorname                                                               
Almond Joy                            0     0    1         0         0.465   
Baby Ruth                             0     0    1         0         0.604   
Boston Baked Beans                    0     0    0         1         0.313   
Candy Corn                            0     0    0         1         0.906   
Caramel Apple Pops                    0     0    0         0         0.604   
...                                 ...   ...  ...       ...           ...   
Snickers Crisper                      1     0    1         0         0.604   
Sour Patch Kids                       0     0    0         1         0.069   
Sour Patch Tricksters                 0     0    0         1         0.069   
Starburst                             0     0    0         1         0.151   
Strawberry bon bons                   0     1    0         1         0.569   

                       pricepercent  winpercent  Y  
competitorname                                      
Almond Joy                    0.767   50.347546  1  
Baby Ruth                     0.767   56.914547  1  
Boston Baked Beans            0.511   23.417824  0  
Candy Corn                    0.325   38.010963  0  
Caramel Apple Pops            0.325   34.517681  0  
...                             ...         ... ..  
Snickers Crisper              0.651   59.529251  1  
Sour Patch Kids               0.116   59.863998  1  
Sour Patch Tricksters         0.116   52.825947  1  
Starburst                     0.220   67.037628  1  
Strawberry bon bons           0.058   34.578991  0  

[65 rows x 13 columns]

In [5]:
#отбираем данные для предикторов, удаляя два последних столбца, индекс не включается в данные.
X = pd.DataFrame(train_data.drop(['winpercent', 'Y'], axis=1))

In [6]:
#указываем столбец отклика
y = pd.DataFrame(train_data['winpercent'])

In [7]:
#подключаем модель линейной регрессии из библиотеки sklearn
from sklearn.linear_model import LinearRegression

In [8]:
#обучение модели
reg = LinearRegression().fit(X, y)

In [9]:
#предсказание для конфет введеных вручную
reg.predict([[1, 1, 1, 0, 1, 0, 1, 1, 1, 0.669, 0.456]])

array([[65.1303666]])

In [10]:
#предсказание для конфет из таблицы

#выбираем строку из таблицы
AirHeads = DATA.loc['Air Heads',:].to_frame().T

#отбираем данные для предикторов и выполняем предсказание с помощью модели
reg.predict(AirHeads.drop(['winpercent', 'Y'], axis=1))

array([[51.39969184]])

Значение коэффициента $\theta_0$:

In [11]:
reg.intercept_

array([32.49207971])

Значение коэффициентов $\theta_1, \ldots, \theta_p$:

In [12]:
reg.coef_

array([[ 27.80862379,  13.22742764,  -1.72139799,   9.31066552,
          2.47147143,   9.97210163,  -7.20313458,  -3.36948719,
         -1.92311592,  12.33760078, -10.75867374]])

Задача 1

Перед вами результаты наблюдений длительности нахождения человека в очереди в зависимости от количества людей в этой очереди.

In [13]:
df = pd.DataFrame(
[[1,4,10]
,[2,22,41]
,[3,20,36]
,[4,7,17]
,[5,13,31]
,[6,12,35]
,[7,17,47]
,[8,3,10]
,[9,1,5]
,[10,21,41]]
,columns = ['id','X','Y'])
df

id   X   Y
0   1   4  10
1   2  22  41
2   3  20  36
3   4   7  17
4   5  13  31
5   6  12  35
6   7  17  47
7   8   3  10
8   9   1   5
9  10  21  41

Обучите модель линейной регрессии для прогнозирования и введите указанные параметры.

In [14]:
X=df.X
X=X.values.reshape(-1,1)
y=df.Y

In [15]:
reg = LinearRegression().fit(X, y)

In [16]:
X.mean()

12.0

In [17]:
y.mean()

27.3

In [18]:
y_pred=reg.predict(X)
y_pred.mean()

27.299999999999994

 $\theta_0$:

In [19]:
reg.intercept_

5.456583629893242

 $\theta_1$:

In [20]:
reg.coef_

array([1.8202847])

Оцените точность модели, вычислив  статистику R-квадрат:


In [21]:
from sklearn.metrics import r2_score
r2_score(y, y_pred)


0.8808245804605277

В прилагаемом файле представлены данные, собранные путем голосования за самые лучшие (или, по крайней мере, самые популярные) конфеты Хэллоуина. Обучите модель линейной многомерной регрессии. В качестве предикторов выступают поля: chocolate, fruity, caramel, peanutyalmondy, nougat, crispedricewafer, hard, bar, pluribus, sugarpercent, pricepercent, отклик — winpercent.


В качестве тренировочного набора данных используйте данные из файла, за иключением следующих конфет: Candy Corn, Ring pop. Обучите модель. Если используете Azure ML Studio, укажите random seed = 2019 в параметрах блока Linear Regression.



In [24]:
candies=pd.read_csv('ITMO Week 4 candy-data.csv')
#candies=candies(set_index='competitorname')
#candies=candies.iloc[:,1:]
candies.head()

competitorname  chocolate  fruity  caramel  peanutyalmondy  nougat  \
0      100 Grand          1       0        1               0       0   
1   3 Musketeers          1       0        0               0       1   
2       One dime          0       0        0               0       0   
3    One quarter          0       0        0               0       0   
4      Air Heads          0       1        0               0       0   

   crispedricewafer  hard  bar  pluribus  sugarpercent  pricepercent  \
0                 1     0    1         0         0.732         0.860   
1                 0     0    1         0         0.604         0.511   
2                 0     0    0         0         0.011         0.116   
3                 0     0    0         0         0.011         0.511   
4                 0     0    0         0         0.906         0.511   

   winpercent  Y  
0   66.971725  1  
1   67.602936  1  
2   32.261086  0  
3   46.116505  0  
4   52.341465  1

In [25]:
candies.competitorname.unique()

array(['100 Grand', '3 Musketeers', 'One dime', 'One quarter',
       'Air Heads', 'Almond Joy', 'Baby Ruth', 'Boston Baked Beans',
       'Candy Corn', 'Caramel Apple Pops', 'Charleston Chew',
       'Chewey Lemonhead Fruit Mix', 'Chiclets', 'Dots', 'Dum Dums',
       'Fruit Chews', 'Fun Dip', 'Gobstopper', 'Haribo Gold Bears',
       'Haribo Happy Cola', 'Haribo Sour Bears', 'Haribo Twin Snakes',
       'Hersheys Kisses', 'Hersheys Krackel', 'Hersheys Milk Chocolate',
       'Hersheys Special Dark', 'Jawbusters', 'Junior Mints', 'Kit Kat',
       'Laffy Taffy', 'Lemonhead', 'Lifesavers big ring gummies',
       'Peanut butter M&Ms', 'M&Ms', 'Mike & Ike', 'Milk Duds',
       'Milky Way', 'Milky Way Midnight', 'Milky Way Simply Caramel',
       'Mounds', 'Mr Good Bar', 'Nerds', 'Nestle Butterfinger',
       'Nestle Crunch', 'Nik L Nip', 'Now & Later', 'Payday',
       'Peanut M&Ms', 'Pixie Sticks', 'Pop Rocks', 'Red vines',
       'Reeses Miniatures', 'Reeses Peanut Butter cup', 'Reese

In [26]:
candies_train=candies[((candies.competitorname!='Candy Corn') & ( candies.competitorname!= 'Ring pop'))]
candies_train.competitorname.unique()

array(['100 Grand', '3 Musketeers', 'One dime', 'One quarter',
       'Air Heads', 'Almond Joy', 'Baby Ruth', 'Boston Baked Beans',
       'Caramel Apple Pops', 'Charleston Chew',
       'Chewey Lemonhead Fruit Mix', 'Chiclets', 'Dots', 'Dum Dums',
       'Fruit Chews', 'Fun Dip', 'Gobstopper', 'Haribo Gold Bears',
       'Haribo Happy Cola', 'Haribo Sour Bears', 'Haribo Twin Snakes',
       'Hersheys Kisses', 'Hersheys Krackel', 'Hersheys Milk Chocolate',
       'Hersheys Special Dark', 'Jawbusters', 'Junior Mints', 'Kit Kat',
       'Laffy Taffy', 'Lemonhead', 'Lifesavers big ring gummies',
       'Peanut butter M&Ms', 'M&Ms', 'Mike & Ike', 'Milk Duds',
       'Milky Way', 'Milky Way Midnight', 'Milky Way Simply Caramel',
       'Mounds', 'Mr Good Bar', 'Nerds', 'Nestle Butterfinger',
       'Nestle Crunch', 'Nik L Nip', 'Now & Later', 'Payday',
       'Peanut M&Ms', 'Pixie Sticks', 'Pop Rocks', 'Red vines',
       'Reeses Miniatures', 'Reeses Peanut Butter cup', 'Reeses pieces',
   

In [27]:
candies_test=candies[((candies.competitorname=='Candy Corn') | ( candies.competitorname== 'Ring pop'))]
candies_test.competitorname.unique()

array(['Candy Corn', 'Ring pop'], dtype=object)

In [28]:
X_train=candies_train.iloc[:,1:-2]
X_train.head()

chocolate  fruity  caramel  peanutyalmondy  nougat  crispedricewafer  hard  \
0          1       0        1               0       0                 1     0   
1          1       0        0               0       1                 0     0   
2          0       0        0               0       0                 0     0   
3          0       0        0               0       0                 0     0   
4          0       1        0               0       0                 0     0   

   bar  pluribus  sugarpercent  pricepercent  
0    1         0         0.732         0.860  
1    1         0         0.604         0.511  
2    0         0         0.011         0.116  
3    0         0         0.011         0.511  
4    0         0         0.906         0.511

In [29]:
y_train=candies_train.winpercent
y.head()

0    10
1    41
2    36
3    17
4    31
Name: Y, dtype: int64

Введите предсказанное значение winpercent для конфет Candy Corn, Ring pop и для конфеты с параметрами [1,0,1,0,0,0,0,0,1,0,494, 0.628]:

In [30]:
X_test=candies_test.iloc[:,:-2]
col=X_test.iloc[:,1:]
type(col)
col_df_candy_corn=pd.DataFrame(col.iloc[0,:])
col_df_candy_corn.T
col_df_ring_pop=pd.DataFrame(col.iloc[1,:])


In [31]:
X_test

competitorname  chocolate  fruity  caramel  peanutyalmondy  nougat  \
8      Candy Corn          0       0        0               0       0   
55       Ring pop          0       1        0               0       0   

    crispedricewafer  hard  bar  pluribus  sugarpercent  pricepercent  
8                  0     0    0         1         0.906         0.325  
55                 0     1    0         0         0.732         0.965

In [32]:
#обучение модели
reg = LinearRegression().fit(X_train, y_train)

In [33]:
reg.predict(col_df_candy_corn.T)

array([40.28254027])

In [34]:
reg.predict(col_df_ring_pop.T)

array([40.18737766])

In [35]:
reg.predict([[1,0,1,0,0,0,0,0,1,0.494, 0.628]])

array([56.24250119])